# Generated by Django 6.0.1 on 2026-01-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_id', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('depth', models.FloatField()),
                ('temperature', models.FloatField()),
                ('salinity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['float_id'], name='core_argopr_float_i_ef2f27_idx'), models.Index(fields=['timestamp'], name='core_argopr_timesta_2128c3_idx')],
            },
        ),
    ]
